### PR TITLE
Update and rename README.md to Modified Doc

### PR DESCRIPTION
**Pull request by Vicky-Raghuwanshi**

### CODE REVIEW

**Comment by hamishwillee** [comment]
Hi @Vicky-Raghuwanshi 

These changes appear to add no real value, so I am closing. If you want changes to be accepted, it is a good idea to explain how they help.

Regard
Hamish

**Comment by chrisdavidmills** [comment]
@Vicky-Raghuwanshi Can I ask, why are we getting so many garbage pull requests against our repos? Is this part of some kind of college or university course?

**Comment by Vicky-Raghuwanshi** [comment]
Actually, it's the Hacktoberfest by DigitalOcean in which we have to make
at least 4 PR  , so after completing it we get some DigitalOcean
Swags/Tees/Strikers.

**Comment by hamishwillee** [comment]
Hi @Vicky-Raghuwanshi,
I think that DigitalOcean are hoping that you will make 4 **useful** contributions, not create more work for open source projects. There are plenty of things that you might do to help; they will of course require that you put some time and effort in.

**Pull request closed without merging**
