### PR TITLE
Updated book detail template to use join tag

### PR DESCRIPTION
**Pull request by thiagojobson**
Updated book detail template to use the builtin [join](https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#join) tag instead of a for loop.

### CODE REVIEW

**Comment by hamishwillee** [comment]
This is certainly more elegant. I assume you tested this?

Will also need corresponding update in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views

**Comment by thiagojobson** [comment]
Yes, I tested it. This renders exactly the same output. I can update the tutorial site once this is merged.

Thanks.

**Comment by hamishwillee** [comment]
Thanks, merged!

**Comment by thiagojobson** [comment]
Thanks, I updated the tutorial site.

**Comment by hamishwillee** [comment]
Thanks very much!

**Pull request merged**
